### ISSUE TITLE
Passthrough is resulting in error in native code for react native

### ISSUE THREAD

**Issue by karthikpala** [miragejs/miragejs#814] opened 2021-03-05 05:48 UTC
Hi,

I was trying to setup mirage in a react native application as shown below for development using API stubs
Since I am integrating mirage in an existing application, I am using pass through to allow the API calls which are available in the backend already.

```
export function makeServer({environment = 'development'} = {}) {
return createServer({
    routes() {
      this.logging = true;
      this.get(
        `https://my_server/groups`,
        () => {
          return {
            "groupName": "GROUP_NAME"
          };
        }
      );
      //this.passthrough();
      this.passthrough('https://codepush.appcenter.ms/**');
      this.passthrough('https://my_server/**');
    }
  });
}
```

We are seeing the below error when an API call goes through passthrough which is resulting in a Native exception and a failure of the API call

```
Mirage: Passthrough request for GET https://codepush.appcenter.ms/v0.1/public/codepush/update_check
ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
        at com.facebook.react.bridge.ReadableNativeArray.getDouble(ReadableNativeArray.java:91)
        at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:63)
        at com.facebook.react.bridge.JavaMethodWrapper$4.extractArgument(JavaMethodWrapper.java:59)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:355)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:216)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:764)
```

**React Native: 0.61.2
MirageJS: 0.1.41**

**Comment by eliaslecomte** [comment] 2021-03-12 12:12
Having the same issue with miragejs 0.1.41 & react-native 0.63.4.

**Comment by kadiryaka** [comment] 2021-03-16 13:04
same issue
miragejs 0.1.41
react-native 0.64

**Comment by diegonava6** [comment] 2021-04-10 06:40
Same issue 
MirageJS 0.1.41
ReactNative 0.63.3

**Comment by strdr4605** [comment] 2021-04-22 12:56
Any progress on this?

**MirageJS** `0.1.41`
**ReactNative** `0.63.2`

**Comment by Gitarcitano** [comment] 2021-05-06 18:29
Same here,

On iOS it works perfectly, on Android shows the same error:

`Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference`

MirageJS `0.1.41`
ReactNative `0.64`

**Comment by elliotmrodriguez** [comment] 2021-05-12 18:45
Same as above. Works on iOS, fails on Android with the Java error already cited.

Mirage 0.1.41
RN 0.63.4

**Comment by ayrtonlacerda** [comment] 2021-05-25 14:36
same issue

**Comment by bouncy-rabbit** [comment] 2021-07-08 07:47
same issue here. any solution?

**Comment by bombillazo** [comment] 2021-07-21 15:34
This issue has screwed me for the past 2 days, I've isolated the problem to the [Pretender](https://github.com/pretenderjs/pretender) dependency, specifically the following line:

```js
  FakeRequest.prototype.passthrough = function passthrough() {
    if (!this.sendArguments) {
      throw new Error('You attempted to passthrough a FakeRequest that was never sent. ' +
            'Call `.send()` on the original request first');
    }
    var xhr = createPassthrough(this, ctx.pretender._nativeXMLHttpRequest);
    xhr.send.apply(xhr, this.sendArguments); // <---- Android does not like!!!!
    return xhr;
  };

```
[Source](https://github.com/pretenderjs/pretender/blob/ddca21671e3e7c69b0be673eb3cd66007931a379/src/interceptor.ts#L36)

If you comment that out, the error goes away, but passthrough does not work. Something must be happening with the sending of that `xhr` object in Android .

Hope this helps unblock this, it's a real blocker for anyone doing React Native. The docs should reflect this state to safe the hassle to other developers.

Honestly though, the Pretender project seems to be almost abandoned, I don't know if @samselikoff and team has plans to continue using it or can help improve one of its main dependencies.

**Comment by samselikoff** [comment] 2021-07-21 17:46
I think the path forward here would be to add a server.handle method (which we had started in https://github.com/miragejs/miragejs/pull/699/files) so you could wire up mirage with different interceptors, like msw or even express. I'm not actively maintaining mirage atm but refactoring away from pretender would be a good next step towards solving this.

**Comment by bombillazo** [comment] 2021-07-21 20:49
Ok everyone, I found the reason for this error. It took waaaaay longer than I expected but I found the root cause. Please refer to this [PR](https://github.com/pretenderjs/pretender/pull/326) in the Pretender repo.  It'd be awesome if this got expedited so feel free to reach out to those necessary to review it.

I must say I learned a lot, and kinda proud I found this, my first but fix on a public project. 😅 

![gold1 3](https://user-images.githubusercontent.com/44002321/126558229-c27c3589-0bf4-430b-aa55-26e5edbff68d.jpg)

**Comment by samselikoff** [comment] 2021-07-22 16:56
Sorry about the rabbit hole but congrats + nice work!! I'd probably add a test in your PR if you want to make it more likely to get merged 👍

**Comment by bombillazo** [comment] 2021-07-27 18:04
This fix was merged: https://github.com/pretenderjs/pretender/pull/326#issuecomment-887204047

**Comment by henrymoulton** [comment] 2021-09-02 13:37
Just for anyone who's using Axios + Mirage and upgrades, you'll run into this issue: https://github.com/pretenderjs/pretender/issues/329

**Closed** 2021-09-23 19:53 UTC
